version: "3.9"

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: recipes
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:5
    environment:
      PMA_HOST: mysql
      PMA_USER: app
      PMA_PASSWORD: app
    ports:
      - "8080:80"
    depends_on:
      - mysql
    restart: unless-stopped

  backend:
    build: ./backend
    environment:
      DATABASE_URL: "mysql://app:app@mysql:3306/recipes?serverVersion=8.0"
      JWT_PASSPHRASE: "dev"
      APP_ENV: "dev"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend/public:/var/www/html/public:ro
    ports:
      - "8000:80"
    depends_on:
      - backend
    restart: unless-stopped

  frontend:
    build: ./frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE_URL: "http://localhost:8000/api"
    restart: unless-stopped

volumes:
  dbdata: {}